# Generated by Django 6.0.5 on 2026-06-23 02:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_pdf', models.FileField(upload_to='cvs_postulaciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('vacante', models.CharField(choices=[('DESARROLLADOR', 'Desarrollador'), ('DISENADOR', 'Diseñador')], max_length=20)),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('pretension_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRESELECCIONADO', 'Preseleccionado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empleo.candidato')),
            ],
        ),
    ]
