# Generated by Django 6.0.6 on 2026-06-24 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0002_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='empleo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
